version: '3'
services:
  fakebook:
    image: kate123wong/fakebook:1.0
    ports:
     - "5000:5000"
    depends_on:
     - db
    container_name: fakebook
    restart: always
  db:
    image: kate123wong/mysql:1.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=6iuVhYwmxC
    restart: always
    container_name: mysql