version: '3'
services:
  fakebook:
    build: web/.
    ports:
     - "5000:5000"
    depends_on:
     - db
    container_name: fakebook
    restart: always
  db:
    build: mysql/.
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=6iuVhYwmxC
    restart: always
    container_name: mysql