version: '3'
services:
  mysql:
    image: "mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=6iuVhYwmxC"
      - "MYSQL_DATABASE=socialcontact"
      - "MYSQL_USER=socialcontact"
      - "MYSQL_PASSWORD=socialcontact123"
    ports:
      - 33069:3306
    container_name: composemysql
 
  fakebook:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - mysql
    container_name: composeweb
