version: '3'
services:
  mysql:
    image: "mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=6iuVhYwmxC"
      - "MYSQL_DATABASE=socialcontact"
      - "MYSQL_USER=socialcontact"
      - "MYSQL_PASSWORD=socialcontact123"
    container_name: mysql
    volumes:
      - "/data:/var/lib/mysql"
    #command: /bin/bash -c "mysql -uroot -p < /home/data.sql&&6iuVhYwmxC"
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
  fakebook:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - mysql
    container_name: fakebook
